language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.4.*
    - php: 5.6
      env: SYMFONY_VERSION=2.5.*
    - php: 5.6
      env: SYMFONY_VERSION=2.6.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
    - php: 7.1
      env: SYMFONY_VERSION=4.1.*

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
  - echo "memory_limit=2G" >> $INI_FILE; # for composer install https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors
  - phpenv config-rm xdebug.ini
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer install --prefer-dist --no-interaction

script: ./vendor/bin/simple-phpunit --coverage-clover build/logs/clover.xml

after_script:
  - ./vendor/bin/test-reporter
